version: '3'

services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: learn
      POSTGRES_PASSWORD: learn
      POSTGRES_DB: db_learn
    volumes:
      - db_data:/var/lib/postgresql/data
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db_data:
